### PR TITLE
refactor: refactor timer code

### PR DESCRIPTION
**Pull request by zhuqingguang**
delete the use of Date.now in remaining delay time calculation

### CODE REVIEW

**Comment by chrisguttandin** [comment]
Hi @zhuqingguang, thanks a lot for your contribution. Could you please also remove the usage of `Date.now()` from here: https://github.com/chrisguttandin/worker-timers-worker/blob/master/src/helpers/timer.ts#L49

Instead of ...
```js
const now = 'performance' in self ? performance.now() : Date.now();
```
... it should be just ...
```js
const now = performance.now();
```
.

**Comment by zhuqingguang** [comment]
I should review the code roundly.  I fix the question but the ci is failed.  
The question is 
> Sauce Connect could not establish a connection
how could i resolve this question?

**Comment by chrisguttandin** [comment]
I think we can ignore the CI for now. The credentials to run the tests on Sauce Labs don't work with pull requests.

Many thanks again for spotting this.

**Comment by chrisguttandin** [comment]
Your changes are published now as v7 of worker-timers-worker. They are also included in the v7 release of worker-timers.

I made this a major version update since it could theoretically break in some older browsers.

**Comment by zhuqingguang** [comment]
> Your changes are published now as v7 of worker-timers-worker. They are also included in the v7 release of worker-timers.
> 
> I made this a major version update since it could theoretically break in some older browsers.

Thank you for your great work!

**Pull request merged**
